### ISSUE TITLE
Loading the obj file overrides the PC value set in testBringup

### ISSUE THREAD

**Issue by jeroendebaat** [chiragsakhuja/lc3tools#18]
https://github.com/chiragsakhuja/lc3tools/blob/628ad01029b2ddcede1acdec3cd355bffe2fd22e/src/test/framework1.cpp#L120-L138

If the PC is set to x3000 in testBringup, as suggested in the documentation, this value if overridden with the ORIG of the asm/obj file when the latter is loaded.

I believe this has been corrected in the new framework, but this bug may be relevant to those who haven't upgraded yet.

**Comment by chiragsakhuja** [comment]
Good catch!  I've fixed this.
