### ISSUE TITLE
v2.0.0 error messages

### ISSUE THREAD

**Issue by owenkaser** [chiragsakhuja/lc3tools#20]
Using 2.0.0 on both the Windows and Linux versions, all assembly errors I have tried (invalid operation,   reference to undefined label) result in "caught exception: assembly failed" with no further diagnostics for novice  programmers such as the nature of the error or line number.  Going to get students to revert to 1.0.6 since this is a show-stopper for intro students.  Eg

            .orig x3000
            adc r0,r0,r0
              .end

**Comment by chiragsakhuja** [comment]
Sorry about this!  I must have accidentally committed some debug code.  I've committed the fix and will publish release v2.0.1 with the fix shortly.

**Comment by chiragsakhuja** [comment]
Alright, I've released v2.0.1, which should fix the issue.  Hopefully your students can transition seamlessly to it.  Closing the issue for now.
