### ISSUE TITLE
large (accidentally) decimal constants crash assembler

### ISSUE THREAD

**Issue by owenkaser** [chiragsakhuja/lc3tools#22]
Thanks for the quick fix on my other issue!  

A student wrote a large binary constant but forgot the b prefix, and the result is an assembler crash, rather than an error message.

In 2.0.1, the following crashes the assembler:

    .ORIG x3000
AddCode .FILL 0001000000000000;ADD opcode
    .END

**Comment by chiragsakhuja** [comment]
Fixed.
