### ISSUE TITLE
Editor text size isn't changeable. 

### ISSUE THREAD

**Issue by vmsaif** [chiragsakhuja/lc3tools#23]
For high dpi screen such as surface devices, the editor font size is too small. There should be option to increase font size. The zoom in scales up everything except the editor.

**Comment by chiragsakhuja** [comment]
I think I've made the editor font size properly scale up with DPI.  I'll check on a couple different monitors and close if it looks good.

**Comment by chiragsakhuja** [comment]
I've confirmed that the editor is much easier to read now, and the font size change is checked into the latest v2.0.2 release.  Thanks for catching this!
