### ISSUE TITLE
Register names are allowed as labels

### ISSUE THREAD

**Issue by owenkaser** [chiragsakhuja/lc3tools#24]
The textbook says that registers names are reserved and can't be used as labels, but the assembler accepts them.  I suspect that you COULD distinguish based on context, but when a student uses a register name as a label, they are probably thinking that somehow they can .FILL a register that way.  Better to be illegal.

**Comment by chiragsakhuja** [comment]
This makes sense, and I can either make it show up as a warning or cause an assembler error.  Which do you think makes more sense?  I generally err on the side of warnings because I feel like they guide newer students better, but in this case the textbook does explicitly state it's illegal.

**Comment by owenkaser** [comment]
Either a warning or an error would be fine.  I'd lean toward error because my students often tend to ignore assembler or compiler warnings.

**Comment by chiragsakhuja** [comment]
Fixed.
