### ISSUE TITLE
Product deployment via SCCM

### ISSUE THREAD

**Issue by kdelacueva** [chiragsakhuja/lc3tools#29]
Due to the Windows' installer auto-installing to %appdata% when using SCCM to deploy the program to a lab it always fails. 

What is your suggestion on how to deploy this program to a lab setting of 100 computers  with 1000 students.

**Comment by chiragsakhuja** [comment]
I'm not familiar with SCCM or deployment in general, but I believe that I can export LC3Tools as a standalone portable package.  Would that be helpful?  If so, I can start adding that to the regular list of export formats.

**Comment by kdelacueva** [comment]
That would be EXTREMELY helpful. Especially if you can make it as a MSI package. That would allow me to a one click and done deployment to a lab. 

In this instance, would you be able to have it install into C:\Program Files\LC3Tools? That would allow sysadmins to bypass the large %appdata% folders and the hundreds of copies of LC3Tools that would invariably happen when deploying there.

%appdata% is a wonderful folder for a single user system. Terrible for shared/lab systems.

**Comment by chiragsakhuja** [comment]
Alright, got it.  Electron-builder also supports MSI, so I'll see if I can set that up like you said.  I'll likely upload the portable version as well if I don't run into trouble with it.  I should have some time to put into this over this weekend.

**Comment by kdelacueva** [comment]
Thank you so much. I really appreciate it!

**Comment by chiragsakhuja** [comment]
I couldn't figure out how to set up the MSI, but I have now packaged a portable version on Windows in the latest v2.0.2 release. This version is just a single standalone executable file. From now on in the Releases tab, there will be two executable options: LC3Tools-Setup-<VERSION>.exe is the self-installing executable that puts LC3Tools into AppData, and LC3Tools-<VERSION>.exe is the standalone, portable executable.

If this meets your criteria, I'll close this issue.

**Comment by kdelacueva** [comment]
I will run a test deployment shortly.

**Comment by kdelacueva** [comment]
Hello Chirag,

Sorry for the long time between this response. This works perfectly. I needed to ensure that it didn't cause any issues in the lab environment. This worked out wonderfully.

Thank you,
Kevin de la Cueva
Information Technology Consultant
College of Natural Sciences, JB351
California State University, San Bernardino
5500 University Parkway, San Bernardino, CA, 92407
(909) 537-5422

________________________________

**Comment by chiragsakhuja** [comment]
Great to hear! I'll put out the portable version with all future releases.
