### ISSUE TITLE
Lexer is confused by semicolons embedded in strings

### ISSUE THREAD

**Issue by owenkaser** [chiragsakhuja/lc3tools#9]
(Version downloaded from Github a couple of weeks ago)
The source code for 
	.orig x3000
	.stringz "before;after"
	.end

shows that the semicolon is treated as beginning a comment.

When assembled and loaded into memory: 

> mem 0x3000 0x3020
0x3000: 0x0062 b
0x3001: 0x0065 e
0x3002: 0x0066 f
0x3003: 0x006F o
0x3004: 0x0072 r
0x3005: 0x0065 e
0x3006: 0x0000 	.stringz "before
0x3007: 0x0000 
.......

**Comment by chiragsakhuja** [comment]
Sorry for the lengthy delay.  I was working on a complete rewrite of the simulator backend on a separate branch and didn't have the bandwidth to fix this issue, as minor as it was.  I've fixed this issue in da249e6867f53f4894f085e49971d9c11b45a4ca.
